export const UNIT_ERROR_CODES = Object.freeze({
  UNIT_NOT_FOUND: "UNIT_NOT_FOUND",
  AMBIGUOUS_UNIT: "AMBIGUOUS_UNIT",
  DIMENSION_MISMATCH: "DIMENSION_MISMATCH",
  LOCATION_INSUFFICIENT: "LOCATION_INSUFFICIENT",
  LOCATION_AMBIGUOUS: "LOCATION_AMBIGUOUS",
  ENTITLEMENT_REQUIRED: "ENTITLEMENT_REQUIRED",
  RELATIONSHIP_UNCONFIRMED: "RELATIONSHIP_UNCONFIRMED",
  INVALID_RELATIONSHIP: "INVALID_RELATIONSHIP",
  DISCONNECTED_FAMILY: "DISCONNECTED_FAMILY",
  CYCLE_DETECTED: "CYCLE_DETECTED",
  ANCHOR_REQUIRED: "ANCHOR_REQUIRED",
  MULTIPLE_ANCHORS_FORBIDDEN: "MULTIPLE_ANCHORS_FORBIDDEN",
  TOOL_AREA_RELATION_REQUIRED: "TOOL_AREA_RELATION_REQUIRED",
  IMPORT_INVALID: "IMPORT_INVALID",
  PROFILE_VERSION_CONFLICT: "PROFILE_VERSION_CONFLICT",
});

export class UnitEngineError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "UnitEngineError";
    this.code = code;
    this.details = details;
  }
}

export const unitError = (code, message, details) =>
  new UnitEngineError(code, message, details);
